### ISSUE TITLE
.storage.type is overriding coloring for variables

### ISSUE THREAD

**Issue by arahansen** [JesseLeite/an-old-hope-syntax-atom#7]
var and let have the storage and type classes which results in the light-gray color being selected.

The result is essentially no syntax highlighting for these keywords. I found that removing the .storage.type light gray selector results in the desired behavior for me.

I'm not sure if that selector is used elsewhere that I'm not thinking of though.

https://github.com/JesseLeite/an-old-hope-syntax-atom/blob/d8439817d55983843422d22ef59dbb5ca53c076d/styles/base.less#L111

**Comment by kfalkiewicz** [comment]
Same here. It looks odd.

**Comment by jesseleite** [comment]
@arahansen @Nosenation: I agree with this one, but changing `.storage.type` has an unwanted effect in other languages such as PHP.  Anyway I checked scope on `var` and `let` in Javascript, and believe I fixed by styling `.storage.type.var`.  with [this commit](https://github.com/JesseLeite/an-old-hope-syntax-atom/blob/a5e926243c7ee2408d98b9daf42c82458313a6e7/styles/base.less#L121-L123).

Enjoy, and thanks for reporting :)

**Comment by kfalkiewicz** [comment]
@JesseLeite I have last version and problem still is visible when var is in global scope (like in gulpfile.js).

![zrzut ekranu 2016-02-05 o 20 36 18](https://cloud.githubusercontent.com/assets/1431712/12857081/7700d84a-cc48-11e5-93fc-6e0fe4a67489.png)

**Comment by jesseleite** [comment]
@Nosenation I see red as expected in my gulpfile.js:

![example](http://b3.ms/BW8Mqg65AoPL)

You even have yellow `require` calls, which isn't intended.  I notice at bottom, the syntax mode in your editor says `JavaScript with JSX`.  I don't have that grammar mode installed.  Try switching your grammar mode by opening command palette > `Grammar Selector` > `JavaScript`:

![grammar](http://b3.ms/WrLA6d0bMNP8)

Other grammar modes will often do their own thing.

**Comment by kfalkiewicz** [comment]
Hmm, you are right. My bad. On normal syntax everything is ok :)

**Comment by jesseleite** [comment]
Awesome :+1:
